server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - en-US
  pretty_print: true
  limits:
    default_items: 20
    max_items: 50
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  admin: false

logging:
  level: INFO

metadata:
  identification:
    title:
      en: OGC API
    description:
      en: OGC API er en ny generasjon standarder fra Open Geospatial Consortium.
    keywords:
      en:
        - OGC
        - Geospatial
        - Geodata
        - Data
        - API
    keywords_type: theme
    terms_of_service: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
    url: https://www.dibk.no

  license:
    name: Norge digitalt-lisens
    url: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
  provider:
    name: Direktoratet for byggkvalitet
    url: https://www.dibk.no
  contact:
    name: Direktoratet for byggkvalitet
    email: post@dibk.no
    url: https://www.dibk.no

resources: {}
