server:
    bind:
        host: 0.0.0.0
        port: 80
    url: ${PYGEOAPI_SERVER_URL:-http://localhost:5000}
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en
    cors: true
    pretty_print: true
    admin: ${PYGEOAPI_SERVER_ADMIN:-false}
    limits:
        default_items: 20
        max_items: 50
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net

logging:
    level: ERROR

metadata:
  identification:
    title:
      en: OGC API - Plandata
    description:
      en: OGC API er en ny generasjon standarder fra Open Geospatial Consortium. På denne serveren tilbys plandata fra Direktoratet for byggkvalitet.
    keywords:
      en:
        - OGC
        - Geospatial
        - Geodata
        - Data
        - API
    keywords_type: theme
    terms_of_service: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
    url: https://www.dibk.no

  license:
    name: Norge digitalt-lisens
    url: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
  provider:
    name: Direktoratet for byggkvalitet
    url: https://www.dibk.no
  contact:
    name: Direktoratet for byggkvalitet
    email: post@dibk.no
    url: https://www.dibk.no

resources:
  reguleringsplaner:
    type: collection
    title:
      en: Reguleringsplaner
    description:
      en: "En reguleringsplan er et arealplankart med tilhørende bestemmelser som fastlegger bruk, flerbruk og vern i bestemte områder, og som gir grunnlag for avklaring av hvilke bygge- og anleggstiltak som kan gjennomføres i planområdet."
    keywords:
      en:
        - Reguleringsplan
        - Arealplan
        - Områdeplan
        - Detaljplan
    extents:
      spatial:
        bbox: [4.626095, 57.977101, 31.125157, 71.188325]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: postgresql_ext.PostgreSQLExtendedProvider
        data:
          host: ${DB_HOST}
          dbname: reguleringsplaner_2025-06-03
          user: postgres
          password: ${DB_PASSWORD}
          search_path: [reguleringsplaner_vn2_60bd26af6c474ba69fb46b875cd6d798]
        id_field: objid
        table: rpomrade_omrade
        geom_field: omrade
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
  kommuneplaner:
    type: collection
    title:
      en: Kommuneplaner
    description:
      en: "Kommuneplanen skal være kommunens overordnede styringsdokument. Den skal gi rammer for virksomhetenes planer og tiltak, og planer for bruk og vern av arealer i kommunen."
    keywords:
      en:
        - Kommuneplan
        - Arealplan
        - Planområde
        - Arealformål
        - Plandata
        - Arealbruk
    extents:
      spatial:
        bbox: [4.087544, 57.759005, 31.349386, 71.351785]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: postgresql_ext.PostgreSQLExtendedProvider
        data:
          host: ${DB_HOST}
          dbname: kommuneplaner
          user: postgres
          password: ${DB_PASSWORD}
          search_path: [kommuneplaner]
        id_field: objectid
        table: kpomrade
        geom_field: shape
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
  kommunedelplaner:
    type: collection
    title:
      en: Kommunedelplaner
    description:
      en: "En kommunedelplan er en delplan under kommuneplanen, og brukes når kommunen trenger å planlegge mer detaljert for et bestemt tema eller et geografisk område."
    keywords:
      en:
        - Kommunedelplan
        - Arealplan
        - Planområde
        - Arealformål
        - Plandata
        - Arealbruk
    extents:
      spatial:
        bbox: [4.776695, 58.046276, 30.887842, 70.712176]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: postgresql_ext.PostgreSQLExtendedProvider
        data:
          host: ${DB_HOST}
          dbname: kommunedelplaner
          user: postgres
          password: ${DB_PASSWORD}
          search_path: [kommunedelplaner]
        id_field: objectid
        table: kpomrade
        geom_field: shape
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
  dokanalyse:
    type: process
    processor:
      name: dokanalyse.DokanalyseProcessor
